<?xml version="1.0" encoding="UTF-8"?>
<testsuites>
  <testsuite name="api" timestamp="2023-03-08T09:27:36Z" hostname="da4435dd6d7f" tests="1" skipped="0" failures="0" errors="0" time="3.919">
    <testcase time="3.919" classname="api" name="API_greets_the_person"/>
  </testsuite>
  <testsuite name="generate_data" timestamp="2023-03-08T09:27:40Z" hostname="da4435dd6d7f" tests="4" skipped="0" failures="0" errors="0" time="0.047">
    <testcase time="0.0350000000000001" classname="generate_data" name="generate_data_works_as_expected"/>
    <testcase time="0.00100000000000033" classname="generate_data" name="generate_data_works_as_expected"/>
    <testcase time="0.00999999999999979" classname="generate_data" name="generate_data_works_as_expected"/>
    <testcase time="0.000999999999999446" classname="generate_data" name="generate_data_works_as_expected"/>
  </testsuite>
  <testsuite name="hello" timestamp="2023-03-08T09:27:40Z" hostname="da4435dd6d7f" tests="1" skipped="0" failures="0" errors="0" time="0.061">
    <testcase time="0.0610000000000008" classname="hello" name="hello_greets_the_entity"/>
  </testsuite>
  <testsuite name="inc_prop" timestamp="2023-03-08T09:27:40Z" hostname="da4435dd6d7f" tests="2" skipped="0" failures="0" errors="0" time="0.035">
    <testcase time="0.0339999999999998" classname="inc_prop" name="inc_prop_works_as_expected"/>
    <testcase time="0.000999999999999446" classname="inc_prop" name="inc_prop_works_as_expected"/>
  </testsuite>
  <testsuite name="prop_trans_inc_dens" timestamp="2023-03-08T09:27:40Z" hostname="da4435dd6d7f" tests="1" skipped="0" failures="0" errors="1" time="0.01">
    <testcase time="0.0100000000000007" classname="prop_trans_inc_dens" name="prop_trans_inc_dens_works_as_expected">
      <error type="error" message="Error in ``[.data.frame`(data, type_of_event == 1 &amp; time_to_event &lt;= tau)`: object 'type_of_event' not found ('test-prop_trans_inc_dens.R:10')">Error in ``[.data.frame`(data, type_of_event == 1 &amp; time_to_event &lt;= tau)`: object 'type_of_event' not found
Backtrace:
 1. savvyr:::prop_trans_inc_dens(data = df, tau = 4)
      at test-prop_trans_inc_dens.R:10:2
 4. base::`[.data.frame`(...)</error>
    </testcase>
  </testsuite>
  <testsuite name="shiny" timestamp="2023-03-08T09:27:40Z" hostname="da4435dd6d7f" tests="1" skipped="0" failures="0" errors="0" time="3.021">
    <testcase time="3.021" classname="shiny" name="The_Shiny_App_returns_a_proper_greeting"/>
  </testsuite>
</testsuites>
